name: Update file in another repo and create PR

on:
  workflow_call:
    inputs:
      api_name:
        description: "Name of the API to update"
        required: false
        type: string
      spec_file_path:
        description: "Path to the specification file in the source repo"
        required: false
        type: string
        default: "api/specification.json"
    secrets:
        TARGET_REPO_TOKEN:
            required: true

env:
    API_NAME: ${{ inputs.api_name }}
jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: source-repo
          fetch-depth: 0

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Hemachandra1233/mvn-test
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo
          fetch-depth: 0

    #   - name: Update file
    #     run: |
    #       ls
    #       pwd
    #       cd target-repo
    #       echo "Updated at $(date)" >> example.txt
    #       cat example.txt

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Check for spec changes
        id: spec-check
        run: |
          cd source-repo
          ls
          echo "Checking for changes in specification.json"
          if git diff --quiet HEAD^ HEAD -- api/specification.json; then
            echo "No changes detected in specification.json. Exiting."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Changes detected in specification.json. Proceeding with update and PR creation."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # - name: Check current directory and list files
      #   if: steps.spec-check.outputs.changed == 'true'
      #   run: |
      #     pwd
      #     ls -la

      - name: Create branch, update spec, commit, push and create a PR
        if: steps.spec-check.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          cd target-repo
          ls
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          for env in dev test uat prod; do
            git checkout $env
            git pull origin $env
            BRANCH_NAME="auto-update-$env-$(date +%s)"
            git checkout -b $BRANCH_NAME
            cp ../source-repo/api/${{inputs.spec_file_path}} ./published-artifacts/apis/$API_NAME/specification.json

            echo "commiting code to target repo"

            git add .
            git commit -m "Spec update $env" || echo "No changes to commit"
            git push origin $BRANCH_NAME

            gh pr create \
                --title "Spec update $env" \
                --body "This PR has spec updates." \
                --base $env \
                --head $BRANCH_NAME

            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          done