name: Docker to Spring example
run-name: ${{ github.actor }} has triggered CD process.
on: 
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: vars.LOGIN_SERVER
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build . -t ${{ vars.LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ github.sha }}
        docker push ${{ vars.LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ github.sha }} 