name: Docker to Spring example
run-name: ${{ github.actor }} has triggered CD process.
on: 
  workflow_dispatch:
  
##  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{ vars.LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ github.sha }}
        docker push ${{ vars.LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ github.sha }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hema-tes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfileDocker }}
        images: 'hemachandratest.azurecr.io/${{ secrets.REGISTRY_USERNAME }}/hello-spring:${{ github.sha }}'