# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - swapnikatest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://hemachandratest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_570ac2701d6e48ed93a73c73737111c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ba7e42c7b47f4eb6b7baf36853ed0e2c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: hemachandratest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_570ac2701d6e48ed93a73c73737111c8 }}/hemachandratest/hello-spring:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'swapnikatest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f17b4ee1b714ec5a49073adf2decc38 }}
        images: 'hemachandratest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_570ac2701d6e48ed93a73c73737111c8 }}/hemachandratest/hello-spring:${{ github.sha }}'