# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - usfdemowebapp(Production), Build and deploy container app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: usfacr.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_5A14149998AE49CAA0B56937B40BDFA8 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_89A45C6E0B2F461392245CD5C4D366C3 }}

    - run: |
        docker build . -t usfacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_5A14149998AE49CAA0B56937B40BDFA8 }}/hemachandratest/hello-spring:${{ github.sha }}
        docker push usfacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_5A14149998AE49CAA0B56937B40BDFA8 }}/hemachandratest/hello-spring:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: usfdemowebapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4904C45519484652AACCF0831D6821A9 }}
        images: usfacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_5A14149998AE49CAA0B56937B40BDFA8 }}/hemachandratest/hello-spring:${{ github.sha }}

