name: Deploy Springboot application on to Azure App Service
run-name: ${{ github.actor }} has triggered CD process.
on: 
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: test
      run: echo "Hello World"
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Build Maven Project
      run: mvn clean package -DskipTests

    - name: Save Jar File to artifact
      run: cd target && ls